### ISSUE TITLE
Not able to configure properly in windows 

### ISSUE THREAD

**Issue by kafleg** [WordPress/theme-review-action#54]
**$ npm run start — --pathToTheme=../polite

> wordpress-theme-check-action@1.4.11 start E:\laragon\www\master\wp-content\themes\theme-review-action
> node bin/program.js "—"

Please ensure docker is running.

Test Version: 1.4.11
Testing Ports: 8484/8485

Steps:
- Copying theme files into the environment...
× Copying theme files into the environment...
Error: Cannot copy '.' to a subdirectory of itself, 'E:\laragon\www\master\wp-content\themes\theme-review-action\test-theme'.
- Checking theme's basic structure
√ Checking theme's basic structure (in 2s 137ms)
- Setting up the development environment for testing...
× Setting up the development environment for testing...
Error: Command failed with exit code 1: npm run install:environment
× Error while running docker-compose command.
chown: cannot access 'wp-config.php': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wordpress-theme-check-action@1.4.11 wp-env: `wp-env "start"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpress-theme-check-action@1.4.11 wp-env script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KafleG\AppData\Roaming\npm-cache\_logs\2021-08-02T07_10_15_788Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wordpress-theme-check-action@1.4.11 install:environment: `npm run install:variables && npm run wp-env start && node bin/configure.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpress-theme-check-action@1.4.11 install:environment script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KafleG\AppData\Roaming\npm-cache\_logs\2021-08-02T07_10_15_978Z-debug.log

> wordpress-theme-check-action@1.4.11 install:environment E:\laragon\www\master\wp-content\themes\theme-review-action
> npm run install:variables && npm run wp-env start && node bin/configure.js

> wordpress-theme-check-action@1.4.11 install:variables E:\laragon\www\master\wp-content\themes\theme-review-action
> node bin/create-wp-env-override.js

Maybe creating .wp-env override config.
No need for an override.

> wordpress-theme-check-action@1.4.11 wp-env E:\laragon\www\master\wp-content\themes\theme-review-action
> wp-env "start"

- Tearing down the environment...
× Tearing down the environment...
Error: Command failed with exit code 1: npm run wp-env destroy
i WARNING! This will remove Docker containers, volumes, and networks associated with the WordPress instance.
× Command failed: docker volume rm $(docker volume ls | grep "a1895f5400360d5fe6cad09f327fd381" | awk '/ / { print $2 }') && docker network rm $(docker network ls | grep "a1895f5400360d5fe6cad09f327fd381" | awk '/ / { print $1 }')
Error: No such volume: $(docker
Error: No such volume: volume
Error: No such volume: ls
awk: cmd. line:1: / / { print $2 })
awk: cmd. line:1:                 ^ syntax error

Error: Command failed: docker volume rm $(docker volume ls | grep "a1895f5400360d5fe6cad09f327fd381" | awk '/ / { print $2 }') && docker network rm $(docker network ls | grep "a1895f5400360d5fe6cad09f327fd381" | awk '/ / { print $1 }')
Error: No such volume: $(docker
Error: No such volume: volume
Error: No such volume: ls
awk: cmd. line:1: / / { print $2 })
awk: cmd. line:1:                 ^ syntax error

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: `docker volume rm $(docker volume ls | grep "a1895f5400360d5fe6cad09f327fd381" | awk '/ / { print $2 }') && docker network rm $(docker network ls | grep "a1895f5400360d5fe6cad09f327fd381" | awk '/ / { print $1 }')`,
  stdout: '',
  stderr: 'Error: No such volume: $(docker\n' +
    'Error: No such volume: volume\n' +
    'Error: No such volume: ls\n' +
    'awk: cmd. line:1: / / { print $2 })\n' +
    'awk: cmd. line:1:                 ^ syntax error\n'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wordpress-theme-check-action@1.4.11 wp-env: `wp-env "destroy"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpress-theme-check-action@1.4.11 wp-env script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KafleG\AppData\Roaming\npm-cache\_logs\2021-08-02T07_10_44_149Z-debug.log

> wordpress-theme-check-action@1.4.11 wp-env E:\laragon\www\master\wp-content\themes\theme-review-action
> wp-env "destroy"

? Are you sure you want to continue? Yes
Error: Unable to start environment.
We ran into an error with the test framework.
**

CC @StevenDufresne

**Comment by StevenDufresne** [comment]
Seems related to: 
https://github.com/WordPress/gutenberg/issues/29814
